class StaticPages {
  public static void mainIndex(String title, String version, String outputfn) {
    PrintStream stream = new PrintStream(new File(outputfn))
    stream.println("<html xmlns='http://www.w3.org/1999/xhtml'>")
    stream.println("<head>")
    stream.println("<meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>")
    stream.println("<title>${title}</title>")
    stream.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'/>")
    stream.println("<link href='/css/docbook-toc.css' rel='stylesheet'/>")
    stream.println("<link href='/css/docbook.css' rel='stylesheet' media='screen'/>")
    stream.println("<script src='https://kit.fontawesome.com/498b6706f0.js' type='text/javascript' crossorigin='anonymous'>")
    stream.println("</script>")
    stream.println("<link href='/icon/${title}.png' rel='shortcut icon'/>")
    stream.println("<link href='/css/nineml.css' rel='stylesheet'/>")
    stream.println("<link href='/css/coffeegrinder.css' rel='stylesheet'/>")
    stream.println("<meta http-equiv='refresh' content='2; url=${version}/' />")
    stream.println("</head>")
    stream.println("<body>")
    stream.println("<nav class='top'></nav>")
    stream.println("<main>")
    stream.println("<article class='book division'>")
    stream.println("<h1>${title}</h1>")
    stream.println()
    stream.println("<p>The current documentation is for version")
    stream.println("<a href='/'>${version}</a>. Redirecting you now.</p>")
    stream.println()
    stream.println("</article>")
    stream.println("</main>")
    stream.println("</body>")
    stream.println("</html>")
    stream.close()
  }

  public static void error404(String title, String version, String outputfn) {
    PrintStream stream = new PrintStream(new File(outputfn))
    stream.println("<html xmlns='http://www.w3.org/1999/xhtml'>")
    stream.println("<head>")
    stream.println("<meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>")
    stream.println("<title>${title}: 404 Not Found</title>")
    stream.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'/>")
    stream.println("<link href='/css/docbook-toc.css' rel='stylesheet'/>")
    stream.println("<link href='/css/docbook.css' rel='stylesheet' media='screen'/>")
    stream.println("<script src='https://kit.fontawesome.com/498b6706f0.js' type='text/javascript' crossorigin='anonymous'>")
    stream.println("</script>")
    stream.println("<link href='/icon/${title}.png' rel='shortcut icon'/>")
    stream.println("<link href='/css/nineml.css' rel='stylesheet'/>")
    stream.println("<link href='/css/coffeegrinder.css' rel='stylesheet'/>")
    stream.println("<script src='/js/error.js' defer='defer'></script>")
    stream.println("</head>")
    stream.println("<body>")
    stream.println("<nav class='top'></nav>")
    stream.println("<main>")
    stream.println("<article class='book division'>")
    stream.println("<h1>${title}: 404 Not Found</h1>")
    stream.println()
    stream.println("<p></p>")
    stream.println()
    stream.println("</article>")
    stream.println("</main>")
    stream.println("</body>")
    stream.println("</html>")
    stream.close()
  }

  public static void versionsJson(String current, String nineml, String outputfn) {
    PrintStream stream = new PrintStream(new File(outputfn))
    stream.println("{\"versions\":{")
    stream.println("  \"currentRelease\": \"${current}\",")
    stream.println("  \"ninemlVersion\": \"${nineml}\"")
    stream.println("}}")
    stream.close()
  }
}
